### ISSUE TITLE
How to use my own data set with your code?

### ISSUE THREAD

**Issue by PanZhichen** [anlif/mi-extrinsic-calib#1]
I am attempting to calibrate the extrinsic parameters of my VLP-16 3D lidar w.r.t. a monocular(e.g. Pointgrey), and this method of your laboratory may be of great help to me.
But there are some questions puzzled me when I read your "README" and config files in your 
code folders, so I open this question to consult you and looking foreword to your reply:
    **1) Whether it means that I need to save 3D point cloud received by Lidar in a .txt format before
 hand? And the same operation with .ppm format is needed for the images?
    2) Do I have to use a "mask" since I am using a PointGrey monocular camera and I don't have a
 mask?
    3) Which principle should I observe when collect both image and lidar information? Need each 
sensor run in a specific frame rate? Do I need to let the FOV of camera and lidar as coincide as 
possible? Or any other rules?**

Thanks for your reading an I need your help, any advise would be appreciated, thanks!

**Comment by Ruijin1988** [comment]
got the same question

**Comment by sergiocasaspastor** [comment]
Do you have any update on the questions? thank you

**Comment by anlif** [comment]
Please contact the original author for these types of questions. I'm merely hosting the code here. If you find an answer to your questions, please do submit a pull request to the README or something similar.
